window.ULTIMATE_DATA = {
  appVersion: "3.2.0",
  name: "Scripture Study Ultimate",
  books: [
    ['Genesis','GEN',50,'OT'],['Exodus','EXO',40,'OT'],['Leviticus','LEV',27,'OT'],['Numbers','NUM',36,'OT'],['Deuteronomy','DEU',34,'OT'],
    ['Joshua','JOS',24,'OT'],['Judges','JDG',21,'OT'],['Ruth','RUT',4,'OT'],['1 Samuel','1SA',31,'OT'],['2 Samuel','2SA',24,'OT'],
    ['1 Kings','1KI',22,'OT'],['2 Kings','2KI',25,'OT'],['1 Chronicles','1CH',29,'OT'],['2 Chronicles','2CH',36,'OT'],['Ezra','EZR',10,'OT'],
    ['Nehemiah','NEH',13,'OT'],['Esther','EST',10,'OT'],['Job','JOB',42,'OT'],['Psalms','PSA',150,'OT'],['Proverbs','PRO',31,'OT'],
    ['Ecclesiastes','ECC',12,'OT'],['Song of Solomon','SNG',8,'OT'],['Isaiah','ISA',66,'OT'],['Jeremiah','JER',52,'OT'],['Lamentations','LAM',5,'OT'],
    ['Ezekiel','EZK',48,'OT'],['Daniel','DAN',12,'OT'],['Hosea','HOS',14,'OT'],['Joel','JOL',3,'OT'],['Amos','AMO',9,'OT'],
    ['Obadiah','OBA',1,'OT'],['Jonah','JON',4,'OT'],['Micah','MIC',7,'OT'],['Nahum','NAM',3,'OT'],['Habakkuk','HAB',3,'OT'],
    ['Zephaniah','ZEP',3,'OT'],['Haggai','HAG',2,'OT'],['Zechariah','ZEC',14,'OT'],['Malachi','MAL',4,'OT'],
    ['Matthew','MAT',28,'NT'],['Mark','MRK',16,'NT'],['Luke','LUK',24,'NT'],['John','JHN',21,'NT'],['Acts','ACT',28,'NT'],
    ['Romans','ROM',16,'NT'],['1 Corinthians','1CO',16,'NT'],['2 Corinthians','2CO',13,'NT'],['Galatians','GAL',6,'NT'],['Ephesians','EPH',6,'NT'],
    ['Philippians','PHP',4,'NT'],['Colossians','COL',4,'NT'],['1 Thessalonians','1TH',5,'NT'],['2 Thessalonians','2TH',3,'NT'],['1 Timothy','1TI',6,'NT'],
    ['2 Timothy','2TI',4,'NT'],['Titus','TIT',3,'NT'],['Philemon','PHM',1,'NT'],['Hebrews','HEB',13,'NT'],['James','JAS',5,'NT'],
    ['1 Peter','1PE',5,'NT'],['2 Peter','2PE',3,'NT'],['1 John','1JN',5,'NT'],['2 John','2JN',1,'NT'],['3 John','3JN',1,'NT'],
    ['Jude','JUD',1,'NT'],['Revelation','REV',22,'NT']
  ].map(([name,code,chapters,testament])=>({name,code,chapters,testament})),

  translations: {
    BSB: {name:'Berean Standard Bible',short:'BSB',lang:'English',license:'Public Domain · CC0',status:'open',source:{type:'bsb'},note:'Modern public domain English with Strong’s links to Hebrew and Greek.'},
    KJV: {name:'King James Version',short:'KJV',lang:'English',license:'Public domain in most countries',status:'open',source:{type:'midvash',lang:'en',slug:'kjv'},note:'Classic English Bible. UK Crown rights may apply to commercial printing in the United Kingdom.'},
    WEB: {name:'World English Bible',short:'WEB',lang:'English',license:'Public Domain',status:'open',source:{type:'midvash',lang:'en',slug:'web'},note:'Modern public domain English.'},
    ASV: {name:'American Standard Version',short:'ASV',lang:'English',license:'Public Domain',status:'open',source:{type:'midvash',lang:'en',slug:'asv'},note:'Public domain English translation from 1901.'},
    ESV: {name:'English Standard Version',short:'ESV',lang:'English',license:'Copyright © Crossway',status:'licensed',permissionUrl:'https://www.crossway.org/permissions/',note:'The complete ESV is not bundled. Import an authorized local pack to activate it for Reader and Parallel Bible use.'},
    TAG1905: {name:'Ang Dating Biblia (1905)',short:'ADB1905',lang:'Tagalog',license:'Public Domain',status:'open',source:{type:'getbible',slug:'tagalog'},note:'Public domain Tagalog Bible.'},
    RV1909: {name:'Reina Valera 1909',short:'RV1909',lang:'Español',license:'Public Domain',status:'open',source:{type:'getbible',slug:'valera'},note:'Public domain Spanish Bible.'},
    LSG1910: {name:'Louis Segond 1910',short:'LSG1910',lang:'Français',license:'Public Domain',status:'open',source:{type:'midvash',lang:'fr',slug:'lsg'},note:'Public domain French Bible.'},
    LUT1912: {name:'Lutherbibel 1912',short:'LUT1912',lang:'Deutsch',license:'Public Domain',status:'open',source:{type:'midvash',lang:'de',slug:'luth1912'},note:'Public domain German Bible.'},
    NLT: {name:'New Living Translation',short:'NLT',lang:'English',license:'Copyright · Tyndale House Foundation',status:'licensed',permissionUrl:'https://www.tyndale.com/permissions',note:'The complete NLT cannot be bundled without publisher permission. Import a legally licensed local pack to activate it.'},
    PINOY: {name:'Ang Bible: Pinoy Version',short:'Pinoy',lang:'Filipino / Taglish',license:'Copyright · Philippine Bible Society',status:'licensed',permissionUrl:'https://bible.org.ph/contact-the-philippine-bible-society/',note:'Publisher permission is required before the complete Pinoy Version can be redistributed. A private licensed pack can be imported locally.'}
  },

  sources: {
    bsbDisplayBase:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/display',
    bsbIndexBase:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/index-cc-by',
    lexicon:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/lexicon/combined.json',
    strongsConcordance:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/concordance/strongs-to-verses.json',
    englishConcordance:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/english-concordance/words-to-verses.json',
    places:'https://raw.githubusercontent.com/BSB-publishing/bsb-data-output/main/base/geography/places.jsonl'
  },

  starter: {
    BSB:{
      'Genesis|1':[
        'In the beginning God created the heavens and the earth.',
        'Now the earth was formless and void, and darkness was over the surface of the deep. And the Spirit of God was hovering over the surface of the waters.',
        'And God said, “Let there be light,” and there was light.',
        'And God saw that the light was good, and He separated the light from the darkness.',
        'God called the light “day,” and the darkness He called “night.” And there was evening, and there was morning—the first day.'
      ],
      'Psalms|23':[
        'The LORD is my shepherd; I shall not want.',
        'He makes me lie down in green pastures; He leads me beside quiet waters.',
        'He restores my soul; He guides me in the paths of righteousness for the sake of His name.',
        'Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me.',
        'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.',
        'Surely goodness and mercy will follow me all the days of my life, and I will dwell in the house of the LORD forever.'
      ],
      'John|1':[
        'In the beginning was the Word, and the Word was with God, and the Word was God.',
        'He was with God in the beginning.',
        'Through Him all things were made, and without Him nothing was made that has been made.',
        'In Him was life, and that life was the light of men.',
        'The Light shines in the darkness, and the darkness has not overcome it.'
      ]
    },
    WEB:{
      'Genesis|1':['In the beginning, God created the heavens and the earth.','The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters.','God said, “Let there be light,” and there was light.'],
      'Psalms|23':['The LORD is my shepherd; I shall lack nothing.','He makes me lie down in green pastures. He leads me beside still waters.'],
      'John|1':['In the beginning was the Word, and the Word was with God, and the Word was God.']
    }
  },

  verseOfDay: [
    ['Psalms',23,1],['Proverbs',3,5],['Isaiah',41,10],['Matthew',6,33],['Matthew',11,28],['John',3,16],['John',14,6],['Romans',8,28],['Romans',12,2],['Philippians',4,6],['Philippians',4,13],['2 Timothy',1,7],['Hebrews',11,1],['James',1,5],['1 Peter',5,7]
  ],

  mapPresets: {
    'Bible Lands':['Jerusalem','Bethlehem','Nazareth','Capernaum','Jericho','Damascus','Antioch','Rome','Corinth','Ephesus'],
    'Patriarchs':['Ur','Haran','Shechem','Bethel','Hebron','Beersheba','Egypt'],
    'Exodus':['Rameses','Succoth','Mount Sinai','Kadesh-barnea','Mount Nebo','Jericho'],
    'Jesus’ Ministry':['Bethlehem','Nazareth','Cana','Capernaum','Bethany','Jericho','Jerusalem'],
    'Paul’s World':['Antioch','Tarsus','Philippi','Thessalonica','Athens','Corinth','Ephesus','Caesarea','Rome'],
    'Seven Churches':['Ephesus','Smyrna','Pergamum','Thyatira','Sardis','Philadelphia','Laodicea']
  },

  profiles: {
    Genesis:{genre:'Torah · narrative and origins',setting:'Ancient Near Eastern world',language:'Biblical Hebrew',overview:'Creation, humanity, the spread of nations, and the patriarchal family stories of Abraham, Isaac, Jacob, and Joseph. Genesis establishes covenant, blessing, land, offspring, exile, and God’s purposes for the nations.',themes:['creation','covenant','blessing','faith','providence'],questions:['What does the passage reveal about God?','Which repeated words or patterns shape the scene?','How does the passage move the covenant story forward?']},
    Exodus:{genre:'Torah · narrative and law',setting:'Egypt, wilderness, and Sinai',language:'Biblical Hebrew',overview:'Israel’s deliverance from Egypt, covenant at Sinai, and the construction of the tabernacle. The book joins redemption, worship, holiness, and God’s presence.',themes:['deliverance','covenant','presence','worship','law'],questions:['How does God reveal His name and character?','How do rescue and covenant obligations relate?','What does the tabernacle communicate about divine presence?']},
    Leviticus:{genre:'Torah · priestly instruction',setting:'Israel encamped at Sinai',language:'Biblical Hebrew',overview:'Instructions about sacrifices, priests, ritual purity, holiness, festivals, and covenant life. The book focuses on how a holy God dwells among His people.',themes:['holiness','atonement','worship','purity','priesthood'],questions:['What kind of holiness is in view?','Who performs the action and for whom?','How does the instruction relate to worship and community life?']},
    Numbers:{genre:'Torah · wilderness narrative and law',setting:'From Sinai toward the plains of Moab',language:'Biblical Hebrew',overview:'Census lists, wilderness journeys, rebellion, judgment, and God’s continuing faithfulness as a new generation approaches the land.',themes:['faithfulness','rebellion','wilderness','leadership','promise'],questions:['What pattern of trust or rebellion appears?','How does God respond to Israel’s failure?','What changes from the first generation to the next?']},
    Deuteronomy:{genre:'Torah · covenant speeches',setting:'Plains of Moab before entry into Canaan',language:'Biblical Hebrew',overview:'Moses’ final covenant speeches rehearse Israel’s story, restate the law, and call the people to wholehearted love and obedience before entering the land.',themes:['covenant','love','obedience','memory','choice'],questions:['What is Israel told to remember?','How are love and obedience connected?','What blessings and warnings frame the passage?']},
    Joshua:{genre:'Historical narrative',setting:'Entry and settlement in Canaan',language:'Biblical Hebrew',overview:'Israel crosses the Jordan, fights campaigns in Canaan, receives tribal allotments, and renews covenant commitments.',themes:['promise','land','courage','covenant','inheritance'],questions:['How does the narrative connect with promises in the Torah?','What role does obedience play?','Where does the text emphasize unfinished work or covenant choice?']},
    Judges:{genre:'Historical narrative',setting:'Tribal Israel before the monarchy',language:'Biblical Hebrew',overview:'Cycles of apostasy, oppression, deliverance, and decline show the social and spiritual fragmentation of Israel.',themes:['apostasy','deliverance','leadership','violence','covenant'],questions:['Where is the cycle of rebellion and rescue visible?','How does each judge differ from earlier ones?','What does the narrator show about Israel’s moral decline?']},
    Ruth:{genre:'Narrative novella',setting:'Bethlehem during the period of the judges',language:'Biblical Hebrew',overview:'A family story of loss, loyalty, provision, and redemption that connects Ruth the Moabite with the line of David.',themes:['loyalty','providence','redemption','kindness','Davidic line'],questions:['How is loyal love shown through actions?','Where does providence work through ordinary decisions?','How does the genealogy reshape the story’s significance?']},
    '1 Samuel':{genre:'Historical narrative',setting:'Transition from judges to monarchy',language:'Biblical Hebrew',overview:'Samuel’s ministry, Saul’s rise and failure, and David’s emergence as Israel moves into kingship.',themes:['kingship','obedience','anointing','leadership','heart'],questions:['What makes a leader faithful or unfaithful?','How does the text contrast Saul and David?','What does the narrative say about kingship under God?']},
    '2 Samuel':{genre:'Historical narrative',setting:'Davidic monarchy',language:'Biblical Hebrew',overview:'David’s reign, covenant promise, military success, moral failure, and the painful consequences within his household and kingdom.',themes:['Davidic covenant','kingship','sin','mercy','consequences'],questions:['How does promise coexist with judgment?','What consequences follow David’s choices?','Where does the narrator distinguish political success from moral faithfulness?']},
    '1 Kings':{genre:'Historical narrative',setting:'Solomon and the divided monarchy',language:'Biblical Hebrew',overview:'Solomon’s reign and temple, followed by the division of the kingdom and prophetic confrontation with idolatry.',themes:['temple','wisdom','idolatry','prophets','kingship'],questions:['How does the king respond to covenant demands?','What role do prophets play?','How does worship shape national life?']},
    '2 Kings':{genre:'Historical narrative',setting:'Divided kingdoms through exile',language:'Biblical Hebrew',overview:'The decline of Israel and Judah, prophetic ministries, Assyrian conquest of the north, and Babylonian exile of Judah.',themes:['judgment','prophets','idolatry','exile','faithfulness'],questions:['What reasons does the narrator give for national collapse?','How do prophetic words frame events?','Where does hope remain amid judgment?']},
    '1 Chronicles':{genre:'Genealogy and historical narrative',setting:'Retelling Israel’s story with focus on David',language:'Biblical Hebrew',overview:'Genealogies and a retelling of David’s reign emphasize worship, temple preparation, Levites, and covenant identity for a postexilic audience.',themes:['worship','David','temple','identity','continuity'],questions:['Why are particular genealogies or events emphasized?','How does this account differ in focus from Samuel and Kings?','What prepares for temple worship?']},
    '2 Chronicles':{genre:'Historical narrative',setting:'Solomon through Judah’s exile and return decree',language:'Biblical Hebrew',overview:'Solomon’s temple and the kings of Judah are evaluated especially through worship, reform, and response to prophetic warning.',themes:['temple','reform','prayer','judgment','restoration'],questions:['How does worship affect the evaluation of each reign?','What patterns of reform and relapse recur?','How does the ending point toward restoration?']},
    Ezra:{genre:'Postexilic narrative and documents',setting:'Jerusalem under Persian rule',language:'Hebrew and Aramaic',overview:'Returned exiles rebuild the temple and renew covenant life, while Ezra’s leadership centers on Torah and communal identity.',themes:['return','temple','Torah','identity','restoration'],questions:['What obstacles confront the returnees?','How do worship and Scripture shape renewal?','What tensions accompany restored community life?']},
    Nehemiah:{genre:'Postexilic memoir and narrative',setting:'Jerusalem under Persian rule',language:'Biblical Hebrew',overview:'Jerusalem’s walls are rebuilt and the community undertakes social, covenantal, and worship reforms.',themes:['rebuilding','leadership','covenant','justice','community'],questions:['How does prayer accompany leadership?','What social problems are addressed?','How does physical rebuilding connect with communal renewal?']},
    Esther:{genre:'Diaspora court narrative',setting:'Persian imperial court',language:'Biblical Hebrew',overview:'A Jewish woman becomes queen and, with Mordecai, helps prevent a planned genocide. The story explains the festival of Purim.',themes:['providence','courage','identity','reversal','deliverance'],questions:['Where do reversals drive the plot?','How is Jewish identity negotiated in diaspora?','How does providence appear without explicit divine naming?']},
    Job:{genre:'Wisdom poetry and narrative frame',setting:'A non-Israelite wisdom setting',language:'Biblical Hebrew',overview:'Job’s suffering provokes sustained debate about justice, wisdom, retribution, and the limits of human explanation before God.',themes:['suffering','wisdom','justice','lament','divine sovereignty'],questions:['Which speaker is making the claim?','Does the book later affirm or correct that claim?','How does God’s final response reframe the debate?']},
    Psalms:{genre:'Poetry, prayer, and worship',setting:'Collected across many periods of Israel’s history',language:'Biblical Hebrew',overview:'A five-book collection of prayers and songs including lament, praise, thanksgiving, royal, wisdom, and pilgrimage psalms.',themes:['worship','lament','praise','kingship','trust'],questions:['What type of psalm is this?','Who is speaking and to whom?','What parallelism, imagery, or movement structures the poem?']},
    Proverbs:{genre:'Wisdom sayings and instruction',setting:'Israelite wisdom tradition',language:'Biblical Hebrew',overview:'Instruction about wise living under the fear of the LORD, covering speech, work, sexuality, money, relationships, justice, and character.',themes:['wisdom','character','speech','work','fear of the LORD'],questions:['Is this a general wisdom principle or an absolute promise?','What character contrast is being drawn?','How does the saying fit the larger theme of wisdom?']},
    Ecclesiastes:{genre:'Wisdom reflection',setting:'Voice of Qoheleth reflecting on life under the sun',language:'Biblical Hebrew',overview:'A probing reflection on mortality, work, pleasure, injustice, time, and the limits of human control and knowledge.',themes:['mortality','meaning','work','time','fear of God'],questions:['What does “under the sun” frame in this passage?','Is the speaker describing experience, advice, or final perspective?','How does mortality shape the argument?']},
    'Song of Solomon':{genre:'Love poetry',setting:'Poetic world of court, countryside, and garden imagery',language:'Biblical Hebrew',overview:'A collection of love poems celebrating desire, beauty, mutual affection, longing, and commitment.',themes:['love','desire','beauty','longing','commitment'],questions:['Who appears to be speaking?','What imagery develops attraction and longing?','How does the poem balance desire, absence, and commitment?']},
    Isaiah:{genre:'Prophetic poetry and narrative',setting:'Judah amid Assyrian pressure and later horizons of exile and restoration',language:'Biblical Hebrew',overview:'Judgment, holiness, messianic hope, the nations, servant imagery, and promises of restoration unfold across a large prophetic collection.',themes:['holiness','judgment','hope','Messiah','new creation'],questions:['What historical horizon is in view?','How do judgment and hope interact?','How are Zion, servant, king, or nations portrayed?']},
    Jeremiah:{genre:'Prophetic oracles and narrative',setting:'Judah before and during Babylonian conquest',language:'Hebrew with some Aramaic',overview:'Jeremiah announces covenant judgment, experiences opposition, laments deeply, and also promises restoration and a new covenant.',themes:['judgment','new covenant','prophetic vocation','exile','hope'],questions:['Who is addressed?','What covenant failure is named?','How does restoration emerge within judgment?']},
    Lamentations:{genre:'Poetic laments',setting:'After Jerusalem’s destruction in 586 BC',language:'Biblical Hebrew',overview:'Five poems grieve Jerusalem’s destruction, confess suffering, wrestle with divine judgment, and seek mercy and restoration.',themes:['grief','judgment','lament','hope','memory'],questions:['What grief is voiced rather than explained?','How does poetic structure shape the lament?','Where does hope appear and how is it qualified?']},
    Ezekiel:{genre:'Prophetic visions, signs, and oracles',setting:'Judean exiles in Babylon',language:'Biblical Hebrew',overview:'Ezekiel’s visions address judgment on Jerusalem, God’s glory, individual responsibility, restoration, renewed shepherding, and a transformed temple-land vision.',themes:['glory','judgment','restoration','new heart','temple'],questions:['Is the passage vision, sign-act, oracle, or symbolic description?','What happens to the theme of God’s presence?','How does restoration answer earlier judgment?']},
    Daniel:{genre:'Court narratives and apocalyptic visions',setting:'Diaspora under foreign empires',language:'Hebrew and Aramaic',overview:'Stories of faithful Jewish life in imperial courts are paired with symbolic visions about kingdoms, persecution, divine rule, and final vindication.',themes:['faithfulness','kingdoms','sovereignty','apocalypse','vindication'],questions:['Which genre is operating in this chapter?','What symbols are interpreted within the text itself?','How does the vision encourage faithfulness under empire?']},
    Hosea:{genre:'Prophetic poetry and symbolic narrative',setting:'Northern kingdom before Assyrian conquest',language:'Biblical Hebrew',overview:'Hosea uses marriage imagery to expose covenant unfaithfulness while repeatedly returning to God’s persistent love and promised restoration.',themes:['covenant love','unfaithfulness','judgment','restoration','knowledge of God'],questions:['How does family or marriage imagery function?','What covenant charges are made?','Where does mercy interrupt judgment?']},
    Joel:{genre:'Prophetic poetry',setting:'Judah in the aftermath or threat of devastating locust plague',language:'Biblical Hebrew',overview:'A national catastrophe becomes a call to repentance and a vision of the day of the LORD, restoration, and the outpouring of God’s Spirit.',themes:['day of the LORD','repentance','Spirit','restoration','judgment'],questions:['How does the plague imagery develop?','What response is called for?','How does the promise of the Spirit broaden the horizon?']},
    Amos:{genre:'Prophetic oracles and visions',setting:'Northern kingdom during a period of prosperity',language:'Biblical Hebrew',overview:'Amos condemns social injustice, corrupt worship, and complacency, insisting that covenant privilege does not cancel accountability.',themes:['justice','judgment','worship','covenant responsibility','restoration'],questions:['What social wrong is named?','How are worship and justice connected?','What remains after the visions of judgment?']},
    Obadiah:{genre:'Prophetic oracle',setting:'Judgment against Edom after violence toward Judah',language:'Biblical Hebrew',overview:'A short oracle condemns Edom’s pride and violence and looks toward the day of the LORD and Zion’s restoration.',themes:['pride','violence','judgment','day of the LORD','restoration'],questions:['What actions of Edom are condemned?','How does poetic reversal work?','How does Edom’s judgment expand into a wider day-of-the-LORD horizon?']},
    Jonah:{genre:'Prophetic narrative',setting:'Israel and the Assyrian city of Nineveh',language:'Biblical Hebrew',overview:'The prophet Jonah resists a mission to Nineveh, exposing tensions around mercy, enemies, repentance, and the wideness of God’s compassion.',themes:['mercy','mission','repentance','prophetic resistance','nations'],questions:['How does Jonah contrast with other characters?','What does the story reveal about divine compassion?','Why does the book end with a question?']},
    Micah:{genre:'Prophetic poetry',setting:'Judah and Israel during Assyrian expansion',language:'Biblical Hebrew',overview:'Micah alternates judgment and hope, condemns exploitation, announces Zion’s humiliation and restoration, and anticipates a ruler from Bethlehem.',themes:['justice','judgment','hope','Zion','Messiah'],questions:['Who is being confronted?','How do city and shepherd images function?','Where does hope answer the book’s accusations?']},
    Nahum:{genre:'Prophetic poetry',setting:'Oracle against Nineveh before its fall',language:'Biblical Hebrew',overview:'Nahum announces the downfall of Assyria’s capital, portraying divine justice against a violent imperial power.',themes:['judgment','empire','justice','violence','deliverance'],questions:['How is imperial violence described?','What imagery portrays Nineveh’s fall?','How would this oracle sound to peoples oppressed by Assyria?']},
    Habakkuk:{genre:'Prophetic dialogue and prayer',setting:'Judah amid rising Babylonian power',language:'Biblical Hebrew',overview:'Habakkuk questions God about injustice and Babylonian violence, receives a call to faithful endurance, and ends in a psalm of trust.',themes:['faith','justice','waiting','lament','trust'],questions:['What question is the prophet asking?','How does the divine answer complicate the problem?','What changes between complaint and final prayer?']},
    Zephaniah:{genre:'Prophetic poetry',setting:'Judah during the reign of Josiah',language:'Biblical Hebrew',overview:'Zephaniah warns of the day of the LORD, calls for humility, and ends with promises of purified worship and restored joy.',themes:['day of the LORD','judgment','humility','remnant','restoration'],questions:['How broad is the announced judgment?','Who is called to seek the LORD?','How does the final restoration reverse earlier imagery?']},
    Haggai:{genre:'Postexilic prophetic messages',setting:'Jerusalem in the early Persian period',language:'Biblical Hebrew',overview:'Haggai urges the returned community to rebuild the temple and connects renewed obedience with covenant hope.',themes:['temple','priorities','obedience','presence','hope'],questions:['What priorities are being challenged?','How are present hardship and covenant response related?','What future hope is attached to the rebuilt temple and Davidic line?']},
    Zechariah:{genre:'Prophetic visions and oracles',setting:'Postexilic Jerusalem',language:'Biblical Hebrew',overview:'Night visions, symbolic actions, and later oracles encourage temple rebuilding while opening wider hopes for cleansing, kingship, shepherding, and the future of Zion.',themes:['restoration','visions','Messiah','cleansing','Zion'],questions:['What symbol appears and how is it interpreted?','What immediate postexilic concern is addressed?','How does the passage expand toward future hope?']},
    Malachi:{genre:'Prophetic disputation',setting:'Postexilic Judah',language:'Biblical Hebrew',overview:'Malachi confronts corrupt worship, covenant unfaithfulness, and cynical religion while promising a coming messenger and the day of the LORD.',themes:['worship','covenant faithfulness','justice','messenger','day of the LORD'],questions:['What accusation and response structure the dispute?','What covenant relationship is being violated?','What future intervention is promised?']},
    Matthew:{genre:'Gospel narrative and teaching',setting:'First-century Jewish and Greco-Roman world',language:'Koine Greek',overview:'Matthew presents Jesus as Messiah and teacher, highlights fulfillment of Scripture, gathers major teaching blocks, and climaxes in death, resurrection, and worldwide mission.',themes:['kingdom of heaven','fulfillment','discipleship','Messiah','mission'],questions:['How does this passage connect Jesus with Israel’s Scriptures?','What does discipleship require here?','How does the kingdom theme function?']},
    Mark:{genre:'Gospel narrative',setting:'First-century Roman imperial world and Jewish Palestine',language:'Koine Greek',overview:'A fast-moving Gospel centered on Jesus’ authority, misunderstood identity, suffering, the cross, and the costly path of discipleship.',themes:['Son of God','suffering','discipleship','authority','cross'],questions:['Who understands or misunderstands Jesus?','How does the passage move toward the cross?','What does following Jesus look like here?']},
    Luke:{genre:'Gospel narrative',setting:'First-century Jewish and Greco-Roman world',language:'Koine Greek',overview:'Luke narrates Jesus’ ministry with special attention to prayer, the Holy Spirit, the poor and marginalized, women, table fellowship, and God’s saving purpose reaching the nations.',themes:['Spirit','salvation','prayer','outsiders','joy'],questions:['Who receives attention in this scene?','What role do prayer and the Spirit play?','How does the passage advance the journey toward Jerusalem?']},
    John:{genre:'Gospel narrative and theological discourse',setting:'First-century Jewish and Greco-Roman world',language:'Koine Greek',overview:'John presents Jesus through signs, conversations, “I am” sayings, and recurring themes of life, light, witness, belief, glory, love, and truth.',themes:['life','light','belief','glory','Word'],questions:['What sign, claim, or witness is central?','How do misunderstanding and deeper meaning interact?','How does this passage relate Jesus to the Father?']},
    Acts:{genre:'Historical narrative',setting:'Jerusalem to Rome in the first-century Mediterranean',language:'Koine Greek',overview:'Acts traces the Spirit-empowered spread of the gospel from Jerusalem through Judea, Samaria, and the wider Roman world, especially through Peter and Paul.',themes:['Holy Spirit','mission','church','witness','nations'],questions:['How does the Spirit direct the mission?','What boundary is being crossed?','How do speeches interpret events?']},
    Romans:{genre:'Pauline letter',setting:'Christian communities in Rome',language:'Koine Greek',overview:'Romans develops Paul’s gospel around sin, justification, union with Christ, life in the Spirit, Israel and the nations, and transformed communal life.',themes:['gospel','justification','Spirit','Israel','new life'],questions:['What problem is Paul addressing in the argument?','How do “therefore” and “for” connect the logic?','How does doctrine move into communal practice?']},
    '1 Corinthians':{genre:'Pauline letter',setting:'Church in cosmopolitan Corinth',language:'Koine Greek',overview:'Paul addresses division, sexuality, lawsuits, marriage, food offered to idols, worship, spiritual gifts, resurrection, and the shape of cruciform love.',themes:['cross','church unity','holiness','love','resurrection'],questions:['What Corinthian problem is being corrected?','How does the cross reshape status and wisdom?','What principle governs freedom and love?']},
    '2 Corinthians':{genre:'Pauline letter',setting:'Paul’s strained relationship with the Corinthian church',language:'Koine Greek',overview:'A deeply personal letter about suffering, apostolic ministry, reconciliation, generosity, weakness, and divine power.',themes:['ministry','weakness','comfort','reconciliation','generosity'],questions:['What defense or appeal is Paul making?','How does weakness relate to power?','How does the new covenant shape ministry?']},
    Galatians:{genre:'Pauline letter',setting:'Churches in Galatia amid controversy about Torah and Gentile inclusion',language:'Koine Greek',overview:'Paul defends justification in Christ, the Abrahamic promise, freedom from imposing Torah as covenant boundary, and life by the Spirit.',themes:['faith','freedom','Spirit','promise','justification'],questions:['What rival message is Paul opposing?','How does Abraham function in the argument?','What does freedom look like in Spirit-led love?']},
    Ephesians:{genre:'Pauline letter',setting:'Early Christian communities in Asia Minor',language:'Koine Greek',overview:'Ephesians celebrates God’s plan in Christ, unity of Jew and Gentile, the church as Christ’s body, new life, household relationships, and spiritual conflict.',themes:['union with Christ','church','unity','new humanity','spiritual warfare'],questions:['What identity statement comes before the command?','How does Jew-Gentile unity matter here?','How does the cosmic scope connect with daily conduct?']},
    Philippians:{genre:'Pauline letter',setting:'Paul writing from imprisonment to believers in Philippi',language:'Koine Greek',overview:'A warm letter about gospel partnership, joy, humility, suffering, unity, and knowing Christ, with Jesus’ self-emptying as a central model.',themes:['joy','humility','partnership','suffering','Christ'],questions:['How does Paul connect joy with hardship?','What pattern of Christlike humility appears?','How does partnership shape the letter?']},
    Colossians:{genre:'Pauline letter',setting:'Church in Colossae',language:'Koine Greek',overview:'Colossians stresses the supremacy and sufficiency of Christ, new identity, freedom from deceptive teaching, and transformed household and community life.',themes:['supremacy of Christ','new life','wisdom','church','freedom'],questions:['What claim about Christ anchors the passage?','What old and new patterns are contrasted?','How does union with Christ affect practice?']},
    '1 Thessalonians':{genre:'Pauline letter',setting:'Young church in Thessalonica',language:'Koine Greek',overview:'Paul encourages a persecuted congregation in faith, holiness, mutual love, work, and hope in Christ’s return and resurrection.',themes:['hope','holiness','perseverance','resurrection','return of Christ'],questions:['What encouragement is tied to Christ’s return?','How should hope reshape ordinary life?','What pastoral concern motivates the instruction?']},
    '2 Thessalonians':{genre:'Pauline letter',setting:'Church in Thessalonica',language:'Koine Greek',overview:'The letter encourages endurance, corrects confusion about the day of the Lord, and addresses disorderly idleness.',themes:['perseverance','day of the Lord','discernment','work','judgment'],questions:['What confusion about the end is being corrected?','What signs or sequence does the text itself mention?','How does eschatological hope affect work and endurance?']},
    '1 Timothy':{genre:'Pastoral letter',setting:'Instruction for church leadership and order',language:'Koine Greek',overview:'Guidance about teaching, prayer, leadership qualifications, care for different groups, money, and godliness in the household of God.',themes:['sound teaching','leadership','godliness','church order','stewardship'],questions:['What local problem is the instruction addressing?','What qualities matter more than status?','How does doctrine connect with conduct?']},
    '2 Timothy':{genre:'Pastoral letter',setting:'A personal charge to Timothy amid suffering',language:'Koine Greek',overview:'Paul urges Timothy to guard the gospel, endure hardship, handle Scripture faithfully, resist corrupt teaching, and finish ministry courageously.',themes:['endurance','Scripture','gospel','faithfulness','ministry'],questions:['What is Timothy told to guard or pass on?','How is suffering framed?','What images of faithful ministry appear?']},
    Titus:{genre:'Pastoral letter',setting:'Churches in Crete',language:'Koine Greek',overview:'Titus is instructed to appoint leaders, confront harmful teaching, and cultivate good works flowing from God’s saving grace.',themes:['leadership','sound doctrine','good works','grace','community order'],questions:['How does grace produce ethical change?','What kind of leadership is required?','How does the church’s conduct affect its public witness?']},
    Philemon:{genre:'Personal Pauline letter',setting:'Household relationship involving Philemon and Onesimus',language:'Koine Greek',overview:'Paul appeals for Onesimus to be received not merely through social status but as a beloved brother in Christ.',themes:['reconciliation','brotherhood','appeal','forgiveness','social relationships'],questions:['How does Paul persuade rather than command?','What new identity is given to Onesimus?','How might the gospel reshape social power?']},
    Hebrews:{genre:'Sermonic letter / exhortation',setting:'A Christian community under pressure',language:'Koine Greek',overview:'Hebrews presents the superiority of the Son, His priesthood, covenant, sacrifice, and heavenly ministry, while repeatedly exhorting perseverance in faith.',themes:['priesthood','new covenant','sacrifice','faith','perseverance'],questions:['What Old Testament text or institution is being interpreted?','How does “better” function in the argument?','What warning or encouragement follows the theology?']},
    James:{genre:'Wisdom-style Christian letter',setting:'Jewish-Christian communities in the diaspora',language:'Koine Greek',overview:'James emphasizes steadfastness, wise speech, impartiality, care for the poor, active faith, humility, prayer, and integrity.',themes:['wisdom','works','speech','justice','prayer'],questions:['What practical inconsistency is challenged?','How does biblical wisdom shape the command?','What does mature faith look like in action?']},
    '1 Peter':{genre:'General letter',setting:'Christians living as minorities in Asia Minor',language:'Koine Greek',overview:'Peter encourages holy, hopeful witness amid suffering, grounding identity in Christ and in biblical images of God’s people.',themes:['suffering','hope','holiness','identity','witness'],questions:['How does future hope shape present suffering?','What identity language from Israel’s Scriptures is reused?','What kind of witness is encouraged?']},
    '2 Peter':{genre:'General letter',setting:'Churches facing corrupt teaching and skepticism about Christ’s return',language:'Koine Greek',overview:'The letter calls for growth in virtue and knowledge, resists destructive teachers, and defends confidence in apostolic testimony and final judgment.',themes:['knowledge','false teaching','judgment','Scripture','return of Christ'],questions:['What marks the false teachers?','How is apostolic testimony defended?','How should expectation of the end shape conduct?']},
    '1 John':{genre:'General letter / pastoral homily',setting:'Churches troubled by division and competing claims about Jesus and spirituality',language:'Koine Greek',overview:'First John tests authentic Christian life through confession about Jesus, obedience, love, truth, and assurance of eternal life.',themes:['love','truth','assurance','obedience','incarnation'],questions:['What claim is being tested?','How do belief, love, and obedience reinforce one another?','What grounds assurance?']},
    '2 John':{genre:'Short general letter',setting:'A Christian community addressed as the elect lady',language:'Koine Greek',overview:'A brief call to walk in truth and love while refusing support to teachers who deny the coming of Jesus Christ in the flesh.',themes:['truth','love','discernment','incarnation','hospitality'],questions:['How are truth and love joined?','What teaching boundary is being defended?','What does hospitality mean in this missionary context?']},
    '3 John':{genre:'Short personal letter',setting:'Conflict over hospitality and authority in a local church',language:'Koine Greek',overview:'The letter commends Gaius for supporting traveling believers, criticizes Diotrephes, and recommends Demetrius.',themes:['hospitality','truth','leadership','support','character'],questions:['What behavior receives praise or criticism?','How is truth measured in conduct?','What does healthy authority look like?']},
    Jude:{genre:'General letter',setting:'Churches threatened by corrupt infiltrators',language:'Koine Greek',overview:'Jude urges believers to contend for the faith, using vivid biblical and Jewish traditional examples to warn against immoral and rebellious teachers.',themes:['false teaching','judgment','faithfulness','mercy','perseverance'],questions:['Which examples are used and why?','What behaviors identify the opponents?','How are believers told to respond?']},
    Revelation:{genre:'Apocalypse, prophecy, and circular letter',setting:'Seven churches of Asia under Roman imperial power',language:'Koine Greek',overview:'Revelation uses symbolic visions to unveil the sovereignty of God and the Lamb, call churches to faithful witness, judge evil powers, and promise new creation.',themes:['Lamb','worship','witness','judgment','new creation'],questions:['What image or symbol is introduced?','Does the text itself interpret the symbol?','How would this vision strengthen faithful witness in the seven churches?']}
  }
};
